version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: expense_tracker_db
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  expense-service:
    build:
      context: .
      dockerfile: expense-tracker-service/Docker/Dockerfile
    container_name: expense_tracker_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    # optional if you have a .env file
    # env_file:
    #   - .env

volumes:
  postgres_data: